-- Supabase migration: create hostels table

create table if not exists hostels (
  id uuid generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamp with time zone default timezone('utc', now()),
  updated_at timestamp with time zone default timezone('utc', now())
);

alter table hostels enable row level security;

create policy if not exists "Owners can manage own hostels" on public.hostels
  for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

create unique index if not exists hostels_owner_id_name_idx on public.hostels(owner_id, name);

